export const textConstants: any = {
  en: {
    signInUp: {
      WELCOME_MESSAGE: "Welcome Back :)",
      APIFLOW: " ApiFlow",
      APIFLOW_HELPERTEXT: "Please login to manage all your APIs endpoints",
      EMAIL: "E-Mail",
      EMAIL_PLACEHOLDER: "Enter Your E-mail Id",
      PASSWORD: "Password",
      PASSWORD_PLACEHOLDER: "Enter Your Password",
      REMEMBER_ME: "Remember Me",
      FORGOT_PASSWORD: "Forgot password?",
      LOGIN_NOW: "Login Now",
      NEW_TO_APIFLOW: "New to ApiFlow",
      LOGIN_TEXT1: "By continuing, you agree to the",
      LOGIN_TEXT2: "ApiFlow Customer Agreement",
      LOGIN_TEXT3: "for ApiFlow services, and the",
      LOGIN_TEXT4: "Privacy Notice.",
      LOGIN_TEXT5: "This site uses essential cookies. See our",
      LOGIN_TEXT6: "Cookie Notice",
      LOGIN_TEXT7: "for more information.",
      REGISTER_NOW: "Register Now",
      REGISTER: "Register",
      REGISTER_HELPERTEXT: "Enter your company email Id",
      FIRST_NAME: "First Name",
      FIRST_NAME_PLACEHOLDER: "Enter Your First Name",
      LAST_NAME: "Last Name",
      LAST_NAME_PLACEHOLDER: "Enter Your Last Name",
      CONFIRM_PASSWORD: "Confirm Password",
      CONFITM_PASSWORD_PLACEHOLDER: "Enter Your Confirm Password",
      OR: "or",
      FOOTER_MESSAGE: "© 2023, ApliFlow Services. All rights reserved.",
      LOGIN_MICROSOFT: "Login with Microsoft Azure",
      REGISTER_MICROSOFT: "Register with Microsoft Azure",
    },
    pricing: {
      APIFLOW: " ApiFlow",
      PRICING_MESSAGE: "Choose the best plan for your APIs Management",
      DOLLAR: "$",
      MONTH: "/ month",
      MEMBERS: "For up to 5 members",
      COMPLETE_REGISTRATION: "Complete Registration",
    },
    companyRegistration: {
      COMPANY_DETAILS: "Company Details",
      COMPANY_DETAILS_HELPERTEXT: "Enter your company details",
      COMPANY_NAME: " Company name",
      COMPANY_NAME_PLACEHOLDER: "Enter Your Company Name",
      COMPANY_MOBILE_NUMBER: "Your Mobile Number",
      COMPANY_OCCUPATION: " Your Occupation",
      COMPANY_OCCUPATION_PLACEHOLDER: "Please Select Your Occupation",
      COMPANY_WEBSITE: "Company Website",
      COMPANY_WEBSITE_PLACEHOLDER: "Please Enter Your Company Website",
      PROCEED_REGISTRATION: "Proceed Registration",
      CHECKBOX_TEXT1: "Show this to other",
      CHECKBOX_TEXT2: "members on registeration",
      CHECKBOX_TEXT3: "Allow anyone from",
      CHECKBOX_TEXT4: "joins automatically",
      IPROTECT_IN: "Iprotecs.in",
    },
    optVerification: {
      VERIFY_EMAIL: " Verify Email",
      OPT_HELPERTEXT:
        "An otp is sent to your email-id, please check and enter the opt below",
      OTP_PLACEHOLDER: "Enter the OTP Pin",
      VERIFY: "Verify",
    },
    apiManageHeader: {
      CREATE_NEW_PROJECT: "Create New Project",
      CREATE_NEW_SERVICES: "Create New Services",
      IMPORT_FROM_POSTMAN: "Import From Postman",
      IMPORT_FROM_SWAGGER: "Import From Swagger",
      GSEARCHBAR_PLACEHOLDER: "Search projects, APIs..",
      API_PROJECTNAME: "API Project Name",
      VERSION: "Version",
      DESCRIPTION: "Description",
      CANCEL: "Cancel",
      CREATE: "Create",
      IMPORT: "Import",
      SORT_BY: "Sort By",
      HTTP_JSON: "JSON",
      HTTP_SOAP: "SOAP",
      GRAPHQL: "GraphQL",
      GRPC: "gRPC",
      WEB_SOCKET: "WEB SOCKET",
    },
    apiManagementSidebar: {
      API_MANAGEMENT: "API Management",
      DASHBOARD: "Dashboard",
      API_MANAGER: "Api Manager",
      DESIGN_API: "Design Api",
      // ANALYTICS_REPORTS: "Analytics & Reports",
      LOGS: "Logs",
      CHANGE_HISTORY: "Change History",
      MANAGE_TEAMS: "Manage Teams",
      DEVELOPMENT: "Development",
      MENU: "Menu",
      ALL_SERVICES: "All Services",
    },
    apiManagement: {
      TOTAL_PROJECTS: "Total Projects",
      TOTAL_ENDPOINTS: "Total Endpoints",
      TOTAL_REQUESTS: "Total Requests",
      TOTAL_FAILED_REQUESTS: "Total Failed Requests",
      PROJECT_NAME: "Project Name",
      PUBLISHED_ON: "Published On",
      CHANGED_ON: "Changed On",
      ACTION: "Action",
      CLOSE: "Close",
      API_PROJECTNAME: "API Project Name",
      VERSION: "Version",
      DESCRIPTION: "Description",
      STATUS: "Status",
      PUBLISHED_DATE: "Published Date",
      CHANGES_AFTER_PUBLISH: "Changes After Publish",
      PROJECT_KEY_SECRET: "Project Key & Secret -",
      PRIMARY: "PRIMARY",
      KEY: "Key",
      SECRET: "Secret",
      COLON: ":",
      SECONDARY: "SECONDARY",
      LATEST_CHANGE: "Latest Change",
      CHANGE_BY: "Change By",
      GO_TO_PROJECT: "Go To Project",
      API_PROJECT: "API Projects",
      API_PROJECT_TEXT:
        "Api Projects are used to hold set of API collection in manageable way, where developers can easily protect, export , import and versioning group of APIs",
      API_ANALYTICS: "API Analytics",
      DAILY: "Daily",
      WEEKLY: "Weekly",
      MONTHLY: "Monthly",
      YEARLY: "Yearly",
      MODIFIED_BY: "Modified by",
      MODIFIED_ON: "Modified on",
      DOWNLOAD_APP_DOCUMENTATION: "Download app documentation",
      APP_KEY: "App Key",
      DOWNLOAD: "Download",
      EDIT: "Edit",
      CLONE: "Clone",
      SAMPLE_CODE: "Sample code",
      UNLINK: "Unlink",
      DELETE: "Delete",
      AUDIT_LOGS: "Audit Logs",
      CONSOLE_ACCESS_CONTROL: "Console Access Control",
      PUBLISH: "Publish",
      SERVICE_URL: "SERVICE URL",
      INVITE: "Invite",
      DEFAULT_VERSION: "DEFAULT VERSION",
      APP_STATUS: " APP STATUS",
      ENVIRONMENT_STATUS: "ENVIRONMENT STATUS",
      HISTORY_ROLLBACK: "HISTORY & ROLLBACK",
      APP_KEY_SECRET: "App Key & Secret",
      PRIMARY_SMALL: "Primary",
      MODIFIED_ON1: "Modified On",
      MODIFY_BY1: "Modified By",
      SECONDARY_SMALL: "Secondary",
      NAME: "NAME",
      SERVICE_TYPE: "SERVICE TYPE",
      VERSION_CAPS: "VERSION",
      MODIFIED_BY_CAPS: "MODIFIED BY",
      MODIFIED_ON_CAPS: "MODIFIED ON",
      VALUE: "VALUE",
      TEST_VALUE: "TEST VALUE",
      DEFAULT_VALUE: "DEFAULT VALUE",
      DATA_TYPE: "DATA TYPE",
      ENCODE: "ENCODE",
      DESCRIPTION_CAPS: "DESCRIPTION",
      BODY: "Body",
      HEADER: "Header",
      AUTHORIZATION: "Authorization",
      QUERY_PARAMETERS: "Query Parameters",
      SHOW_SERVICE_DETAILS: "Show service Details",
      API_SERVICE_NAME: "API Service Name",
      API_BASE_URL: "API Base URL",
      WEB_SERVICE_AUTHENTICATION: "Web Service Authentication",
      NONE: "NONE",
      BASIC: "Basic",
      NTLM: "NTLM",
      CANCEL: "Cancel",
      SAVE: "Save",
      SAVE_ADD_OPERATIONS: "Save & Add Operations",
      SAVE_GET_RESPONSE: "Save & Get Response",
      API_OPERATION_NAME: "API Operation Name",
      OPERATION_SECURITY_LEVEL: "Operation Security Level",
      API_OPERATION_URL: "API Operation URL",
      API_OPERATION_URL_PLACEHOLDER: "https://sampledomain.com",
      PASS_THROUGH_COOKIES: "Pass-through Cookies",
      NO: "No",
      YES: "Yes",
      GENERATE_MOCK_DATE: "Generate Mock Date",
      INPUT_PARAMETERS: "Input Parameters",
      OUTPUT_PARAMETERS: "Output Parameters",
      ENABLE_PASS_THROUGH: "Enable pass-through:",
      REQUEST: "Request",
      REQUEST_TEMPLATE: "Request Template:",
      SHOW: "Show",
      REQUEST_RESPONSE: "Request & Response",
      INTEGRATION_SERVICE_INPUT: "Integration Service Input",
      INTEGRATION_SERVICE_OUTPUT: "Integration Service Output",
    },
    apiRisk: {
      apiRisk_Table: {
        ENDPOINTS: "Endpoint Details",
        SCANNED_DATE: "Scanned Date",
        RISKS: "Risks",
        ACTIONS: "Actions",
      },

      apiDashboard: {
        API_RISK: "Api Risks",
        RISK_CONTENT:
          "Api Risks are used to hold set of API collection in manageable way, where developers can easily protect, export , import and versioning group of APIs",
        END_POINTDETAILS: "Endpoint Details",
        ALL: "All",
        RISK: "Risk",
        FAILED: "Failed",
        PASSED: "Passed",
        NOT_SCANNED: "Not Scanned",
        PLACE_HOLDER: "Search risky Apis",
      },
      apiRiskheader: {
        CREATE_NEW_SCAN: "Create New Scan",
        PLACE_HOLDER: "Search projects, APIs",
      },
      analyticsgraph: {
        API_ANALYTIC: "Api Analytics",
      },
      vulnerabilities: {
        VULNERABILITIES: "Vulnerabilities",
        NEW_VULNERABLE_APIS: "New Vulnerable APIs",
        SERVICES: "Services with",
        VULNERABILITIES_API: "Vulnerable APIs",
        STATUS: "Status",
        CURRENT: "Current",
        LAST_HOURS: "In Last 24 hours",
      },
      vulnerabilities_Table: {
        SERVICE_VULNERABILITY: "SERVICE/VULRABILITY TYPES",
        API_AFFECTED: "Api Affected",
        CALL_VOLUME: "Call volume",
      },
      sensitiveData: {
        SUMMARY: "Summary",
        SENSITIVE_DATATYPES: "Sensitve data Types",
        API_ENDPOINT_WITH_SENSITIVE: "Api Endpoints with sensitiveData Types",
        OBSERVED_SENSITIVITY: "Observed Sensitivity",
      },
      sensitiveData_table: {
        NAME: "NAME",
        SENSITIVITY: "SENSITIVITY",
        DATA_SETS: "DATA SETS",
        ENDPOINTS: "ENDPOINTS",
        SERVICES: "SERVICES",
        DOMAINS: "DOMAINS",
      },
    },

    apiIntelligence: {
      apiAnalytics: {
        ANALTIC_CONTENT:
          "Select one or more parameters to filter by. the value is case sensitive. (ex :Duration 34 or Service/project name = ERPService)",
        VISUALIZATION: "Visulization",
        RESULTS: "Results",
      },
    },
    apiActivity: {
      ACTIVITY_PLACEHOLDER: "Search",

      apiActivityGraph: {
        TOTALCALLS: "TOTAL CALLS",
      },
    },

    notification: {
      NOTIFICATION: "Notification",
      NOTIFICATION_SETTINGS: "Notification Settings",
      NOTIFICATION_CONTENT1: "You're all caught up",
      NOTIFICATION_CONTENT2: "Time to grab a coffee, or stretch a little",
    },

    settings: {
      SETTINGS: "Settings",
      PROFILE: "Profile",
      ACCOUNT: "Account",
      NOTIFICATIONS: "Notifications",
      API_KEYS: "API keys",
      PROFILE_TEXT: "Profile picture and cover",
      PROFILE_DETAILS: "Profile details",
      PUBLIC_PROFILE: "Public profile",
      MAKE_MY_PROFILE_PUBLIC: "Make my profile public",
      PUBLIC_PROFILE_TEXT:
        "This will allow others to discover you on Postman and learn more about your work.",
      UPDATE_PROFILE: "Update Profile",
      UPDATE_EMAIL_ADDRESS: "Update Email Address",
      PASSWORD: "Password",
      CHANGE_YOUR_PASSWORD: "Change your password.",
      CHANGE_PASSWORD: "Change Password",
      TWO_FACTOR_AUTHENTICATION: "Two-factor authentication",
      TWO_FACTOR_AUTHENTICATION_TEXT:
        "Add an extra layer of security to your account by enabling two-factor authentication.",
      ENABLE_2FA: "Enable 2FA",
      EXPORT_YOUR_DATA: "Export your data",
      EXPORT_YOUR_DATA_TEXT: "Take offline backups of your workspace data.",
      EXPORT_DATA: "Export Data",
      DELETE_YOUR_ACCOUNT: "Delete your account",
      PERMENANTELY_DELETE_YOUR_ACCOUNT: "Permanently delete your Postman data.",
      DELETE_TOAST:
        "You can delete your account after you leave all the teams.",
      DELETE_ACCOUNT: "Delete Account",
      NOTIFICATION_PREFERENCES: "Notification Preferences",
      NOTIFICATION_PREFERENCES_TEXT:
        "Select what and how you want to be notified.",
      GET_NOTIFIIED_IN_STACK: "Get notified in Stack",
      GET_NOTIFIIED_IN_STACK_TEXT:
        "Be informed about what's happening in Postman directly in Stack.",
      CONNECT_TO_STACK: "Connect to Stack",
      NOTIFICATION_HEADER: "Notification",
      VIA_EMAIL: "Via email",
      IN_APP: "In app",
      UPDATE_PREFERENCES: "Update Preferences",
      NO_API_KEYS: "No API Keys",
      API_KEYS_TEXT1:
        "Fetch live Postman data to integrate with your build system and toolchain,",
      API_KEYS_TEXT2:
        "auto-export to your repository, and even create converters.",
      COLLECTION_ACCESS_KEYS: "Collection access keys",
      COLLECTION: "Collection",
      KEY: "Key",
      CREATED_ON: "Created on",
      CREATED_BY: "Created by",
      API_KEYS_TEXT3: "You haven't generated any Collection Access Keys yet",
      API_KEYS_TEXT4:
        "Collection Access Keys allows you to securely grant read-only access to a",
      API_KEYS_TEXT5:
        "single collection. Share any collection to generate a Collection Access Key.",
      SECURITY: "Security",
      SECURITY_TEXT1: "When I publicly expose token",
      SECURITY_TEXT2:
        "When I publicaly expose API Flow API key on GitHub or GitLab",
      POSTMAN_SUMMARY: "API Flow Summary",
      POSTMAN_SUMMARY_TEXT1: "Weekly summary of my  API Flow usage",
      TEAM: "Team",
      TEAM_TEXT1: "Weekly reminders of all requests to join my team",
      PRIVATE_NETWORK_APIS: "Private Network APIs",
      PRIVATE_NETWORK_APIS_TEXT1: "Monthly summary of my APIs",
      PRIVATE_NETWORK_APIS_TEXT2:
        "Monthly summary of new APIs and API versions",
      PUBLIC_API_NETWORK: "Public API Network",
      PUBLIC_API_NETWORK_TEXT1: "Monthly summary",
      PUBLIC_API_NETWORK_TEXT2: "Updates about my published APIs",
      MONITORS: "Monitors",
      MONITORS_TEXT1: "System event that affect scheduled runs",
      MONITORS_TEXT2: "Daily summaries of all my monitors",
      MONITORS_TEXT3: "Weekly summaries of all my monitors",
      COMMENTS: "Comments",
      COMMENTS_TEXT1: "When someone replies to my comment",
      COMMENTS_TEXT2: "When I'm mentioned in a comment",
    },
  },
  es: {
    signInUp: {
      // Add translations for the 'es' language if needed
    },
  },
};
