export const textConstants: any = {
  en: {},
  es: {},
};
export const sigInUpConstants: any = {
  en: {
    LOGO: "API Trail",
    EMAIL_LABEL: "E-Mail Address",
    EMAIL_PLACEHOLDER: "E-Mail ID",
    PASSWORD_LABEL: "Password",
    OR_CONNECT_WITH: "Or connect with",
    LEARN_MORE: "Learn More",
    signin: {
      PASSWORD_PLACEHOLDER: "Enter password",
      TITLE: "Log in on APITrail",
      BUTTON: "Login",
      TEXT: "Don’t have an account?",
      LINK: "Sign Up",
      REMEMBER_ME: "Remember me",
      FORGOT_PASSWORD: "Forgot Password?",
      CHECK_BOX_ROUTE: "/forgot-password",
      LAYOUT_TYPE: "signin",
      RIGHT_SIDE_CONTENT:
        "The best Api's visibility tool for organization. Every api needs authentication and authorization. Api flow make sure all your api's are secure in real time and with AI you get the all the security vulnerabilities covered all the time.",
    },
    signup: {
      PASSWORD_PLACEHOLDER: "Create a password",
      TITLE: "Sign Up on APITrail",
      BUTTON: "Create Account",
      TEXT: "Already a member?",
      LINK: "Login",
      LAYOUT_TYPE: "signup",
      MIXED_TEXT: {
        start: "I agree to the ",
        between: " and the ",
        text1: "Terms of Service",
        text2: "Privacy Policy",
        link1: "/signin",
        link2: "/signin",
      },
      RIGHT_SIDE_CONTENT:
        "The best Api's visibility tool for organization. Every api needs authentication and authorization. Api flow make sure all your api's are secure in real time and with AI you get the all the security vulnerabilities covered all the time.",
    },
    "forgot-password": {
      TITLE: "Forgot Password",
      BUTTON: "Retrieve Password",
      LINK: "< Back to login page",
      LAYOUT_TYPE: "forgot-password",
      RIGHT_SIDE_CONTENT:
        "The best Api's visibility tool for organization. Every api needs authentication and authorization. Api flow make sure all your api's are secure in real time and with AI you get the all the security vulnerabilities covered all the time.",
    },
  },
  es: {},
};
export const onboardingConstants: any = {
  en: {
    LOGO: "API Trail",
    SIGN_OUT: "Sign Out",
    heroSection: {
      TITLE: "Welcome to API Trail",
      DESCRIPTION: "Better API Visibility, Lesser Complexity",
      BUTTON: "Let’s Get Started",
    },
    mailVerification: {
      TITLE: "Confirm your email address",
      SEND_TO: "We sent an email to andrew.pepy@gmail.com",
      DESCRIPTION:
        "Please confirm your email address by clicking the link we just sent to your inbox",
      BUTTON: "Resend verification email",
    },
    signUp: {
      SIGNUP: "Signup",
      SIGNUP_DESCRIPTION: "Provide an email and password",
      WORKSPACE: "Workspace",
      WORSKAPCE_DESCRIPTION: "Create workspace",
      DISCOVERY: "Discovery",
      DISCOVERY_DESCRIPTION: "Discover your API",
      RESOURCES: "Resources Catalog",
      RESOURCES_DESCRIPTION: "Catalog API",
      INVITE_USERS: "Invite Users",
      INVITE_USERS_DESCRIPTION: "Manage your team",
      EMAIL: "Email *",
      USER_NAME: "User Name *",
      FIRST_NAME: "First Name *",
      LAST_NAME: "Last Name *",
      NEW_PASSWORD: "New Password *",
      CONFIRM_PASSWORD: "Confirm Password *",
      SIGNUP_WITH_GOOGLE: "Sign up with Google",
      SIGNUP_WITH_EMAIL: "Sign up with Email",
      SIGNUP_WITH_MICROSOFT: "Sign up with Microsoft",
      SIGNUP_WITH_GITHUB: "Sign up with Github",
      CREATE_YOUR_ACCOUNT: "Create your account",
      CREATE_YOUR_ACCOUNT_DESCRIPTION: "Account creation using SSO or Email",
      CREATE_WORKSPACE: "Create Workspace",
      APITRAIL_ONBOARDING: " API Trail Onboarding",
      SWITCH_TITLE:
        "Create channel for this environment and invite all the team members",
      SWITCH_NAME: "Details",
      DISCOVERY_TYPE: "Discovery Type",
      DISCOVERY_TYPE_DESCRITPION: "Choose discovery method",
      INVITE_USERS_DESC: "Invite your team members",
      INVITED_USERS: "Invited Users",
      INVITED_USERS_DESC: "List of invited users",
      SUCCESSFULL: "Successful",
      SUCCESS_DESC:
        "Your account has successfully created, Now Re-directing to application",
      DISCOVERY_HEADER: "API discovery via Integration",
    },
    signupValidation: {
      CONFIG_NAME: "Configuration Name is required",
      ACCESS_KEY: "Access key is required",
      SECRET_KEY: "Secret key is required",
      REGION_KEY: "Region key is required",
      INTERVAL_KEY: "Interval key is required",
      SWAGGER_URL: "Swagger URL is required",
      SWAGGER_FILE: "Swagger File is required",
    },
    signin: {
      EMAIL: "E-Mail",
      PASSWORD: "Password",
      OTP: "OTP",
      RECOVERY_CODE: "Recovary Code",
      OTP_TEXT1: "If you are unable to access the authenticator app, ",
      USE_RECOVERY_KEY: "use your Recovery Key",
      USE_OTP_INSTEAD: "Use OTP instead?",
      CONTINUE_WITH_GOOGLE: "Continue with Google",
      TWO_FACTOR_AUTHENTICATION: "Two-Factor Authentication",
      ENTER_OTP: "Enter Authenticator app OTP",
      LOGIN_WITH_CREDENTIALS: "Login with your credentials",
    },
    button: {
      BACK: "Back",
      CREATE: "Create",
      NEXT: "Next",
      INVITE: "Invite",
      GO_TO_DASHBOARD: "Go to Dashboard",
      BACK_TO: "Back to",
      VERIFY: "Verify",
      LOGIN: "Login",
    },
    common: {
      OR: "(OR)",
      LOGO: "Onboarding",
      NAME: "Name",
      DESCRIPTION: "Description",
      PROJECT_NAME: "Project Name",
      CONFIGURATION_NAME: "Configuration Name",
      SYNC_INTERVAL: "Sync Interval",
      ACCESS_KEY: "Access Key",
      SECRET_KEY: "Secret Key",
      REGION: "Region",
      SUBSCRIPTION_ID: "Subscription ID",
      TENANT_ID: "Tenant ID",
      IMPORT_TYPE: "Import Type",
      SWAGGER_URL: "Swagger URL",
      SWAGGER_FILE: "Swagger File",
      FILE: "File",
      SELECT_FILE: "Select File",
      NO_DATA_AVAILABLE: "No data available",
      SELECTED: "Selected",
      PROJECT: "Project",
      ENVIRONMENTS: "Environments",
      NO_ENVI_AVAILABLE: "No environments available",
      EMAIL_ID: "E-Mail ID",
      ROLE: "Role",
      ACTION: "Action",
    },
    noDataDescription: {
      NO_DATA_AVAILABLE: "No data available",
      NO_ENVI_AVAILABLE: "No environments available",
      NO_DATA_TABLE: "There is no data available to display in the table.",
    },
    gatewayList: {
      AWS: "AWS Gateway",
      AZURE: "Azure Gateway",
      GCP: "GCP Gateway",
      SWAGGER_NAME: "API Discovery via Swagger URL",
      SWAGGER: "Swagger",
      AWS1: "AWS",
      AZURE1: "AZURE",
      SWAGGER1: "SWAGGER",
      AWS_DESC: "AWS Projects & Environments",
      SWAGGER_DESC: "API discovery via Swagger Import",
      DEFAULT_DESC: "Discovered Projects & Environments",
    },
  },
  es: {},
};
