import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReduxProvider from "./Redux/ReduxProvider";
import "./index.css";
import "bootstrap/dist/css/bootstrap.min.css";
import ClientProvider from "@/Provider/clientProvider";
import MsalProvider from "@/Provider/msalProvider";
import { Suspense } from "react";

import ConsoleLogProvider from "@/Provider/consoleLogProvider";

import SessionWrapper from "@/Provider/sessionProvider";
import DashboardLayout from "./apiflow_Pages/layout/dashboardLayout";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "ApiFlow", // Updated title
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/Assests/images/cloneImage.png" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ReduxProvider>
          <MsalProvider>
            <ConsoleLogProvider>
              <ClientProvider>
                <SessionWrapper>
                  <Suspense>
                    <DashboardLayout>{children}</DashboardLayout>
                  </Suspense>
                </SessionWrapper>
              </ClientProvider>
            </ConsoleLogProvider>
          </MsalProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
