// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";
// import ReduxProvider from "./Redux/ReduxProvider";
// import "./index.css";
// import "bootstrap/dist/css/bootstrap.min.css";
// import ClientProvider from "./clientProvider";
// import MsalProvider from "./msalProvider";
// import { Suspense } from "react";
// import GlobalLoader from "./Components/Global/GlobalLoader";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         <ReduxProvider>
//           <MsalProvider>
//             <ClientProvider>{children}</ClientProvider>
//           </MsalProvider>
//         </ReduxProvider>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReduxProvider from "./Redux/ReduxProvider";
import "./index.css";
import "bootstrap/dist/css/bootstrap.min.css";
import ClientProvider from "@/Provider/clientProvider";
import MsalProvider from "@/Provider/msalProvider";
import { Suspense } from "react";
import GlobalLoader from "./Components/Global/GlobalLoader";
// Import your SVG icon for other uses, but not as a favicon
import UserV2Icon from "./Assests/icons/v2UserIcon.svg";
import ConsoleLogProvider from "@/Provider/consoleLogProvider";
import { SessionProvider } from "next-auth/react";
import SessionWrapper from "@/Provider/sessionProvider";
import DashboardLayout from "./apiflow_Pages/layout/dashboardLayout";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "ApiFlow", // Updated title
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/Assests/images/cloneImage.png" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ReduxProvider>
          <MsalProvider>
            <ConsoleLogProvider>
              <ClientProvider>
                <SessionWrapper>
                  <Suspense>
                    <DashboardLayout>{children}</DashboardLayout>
                  </Suspense>
                </SessionWrapper>
              </ClientProvider>
            </ConsoleLogProvider>
          </MsalProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
